In [1]:
import re

In [12]:
def checkmail(email):
    regex = '^[a-zA-Z0-9]+[@][a-z]+[.][a-z]{2,3}$'  
    if(re.search(regex, email)):
        return 'valid'
    else:
        return 'invalid'
    #complete the function
    #the function should return the strings "invalid" or "valid" based on the email ID entered


In [17]:
email=input()
print(checkmail(email))

1harish@accenture.co1
invalid


# Question 2

In [18]:
list1 = [[1,2,3],[4,5],[6,7,8,9]]

In [20]:
print(list1)

[[1, 2, 3], [4, 5], [6, 7, 8, 9]]


In [24]:
new_list = []
for item in list1:
    new_list += item

print(new_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# Question 3

In [34]:
list1 = [1,2,3,4,5,6]

for index, item in enumerate(list1):
    if item % 3 == 0:
        list1[index] = item * item

print(list1)


[1, 2, 9, 4, 5, 36]


In [33]:
5%3

2

# Question 4

In [49]:
n = 9
n = str(n)
cal = int(n)
for i in [[1],[1,1],[1,1,1]]:
    m = n
    for j in i:
        m = m+''+n  
#     print(m)
    cal+=int(m)
#     print(cal)

print(cal)

11106


In [41]:
n = str(3)
cal = int(n)
print(cal)

3


In [48]:
9+99+999+9999

11106

# Question 5

In [50]:
string ='aadddcb'
n = 2

In [71]:
char_dict = {}
for char in string:
    if char_dict.get(char):
        char_dict[char] = char_dict[char] + 1 
    else:
        char_dict[char] = 1

print(char_dict)
char_dict = sorted(char_dict.items(), key=lambda x: x[1], reverse=True)    
print(char_dict)

list_char = []
count = 1
for i in char_dict:
    if count <= n:
        list_char.append(i[0])
        count+=1
    else:
        break

print(list_char)

{'a': 2, 'd': 3, 'c': 1, 'b': 1}
[('d', 3), ('a', 2), ('c', 1), ('b', 1)]
['d', 'a']


In [55]:
char_dict = {}

In [53]:
type(char_dict)

dict

In [56]:
?char_dict

In [57]:
help(char_dict)

Help on dict object:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Built-in subclasses:
 |      StgDict
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>va

# Question 6

In [72]:
import numpy as np
x=int(input())
y=int(input())
#write your code here
def d_array(r,c):
    array = [[(i+j)/2 for j in range(y)] for i in range(x)]
    a = np.matrix(array)
    return a

print(d_array(x,y))

3
4
[[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]


In [73]:
print(range(5))

range(0, 5)


In [75]:
for i in range(4):
    print(i)

0
1
2
3


In [77]:
x = 3
y = 4
t = x * y
np.arange(t).reshape(x,y)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
list1 = []
for a in range(x):
    for b in range(y):
        list1.append((a+b)/2)

print(list1)
print(np.matrix(list1).reshape(x,y))
    

[0.0, 0.5, 1.0, 1.5, 0.5, 1.0, 1.5, 2.0, 1.0, 1.5, 2.0, 2.5]
[[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]
